#++
#  DESCRIPTION: Settings for Network-to-Serial gateway
#
#  AUTHOR: Ruslan R.  Laishev
#
#  CREATION DATE: 11-FEB-2026
#
#  MODIFICATION  HISTORY:
#
#--


#
#
#

listeners = (					# A listeners to accept remote request, pass to local device, and return response
	{
	bind = "TCP:0.0.0.0:502";		# Listen on the port TCP #502
	connlm = 8;				# A maximum number of connections from remote clients
	iotmo = 5000;				# A timeout for network I/O operations, milliseconds
	target = "/dev/ttyUSB0";		# Target serial (must be defined in the <serials> section!)
	},

	{bind = "TCP:0.0.0.0:503"; connlm = 8; iotmo = 5000; target = "/dev/ttyUSB1";},
	# {bind = "TCP:0.0.0.0:504"; connlm = 8; iotmo = 5000; target = "/dev/ttyS0";}
);



serials = (
	{	desc = "MicroVAX 3100 OPA0: Console";
		device = "/dev/ttyUSB0";	# OS device name, eg: COM1, /dev/ttyS0 ...
		chars = "9600, 8, N, 1";	# <Speed, bits in byte, parity checking, stop bits>
		flow = "NONE";			# Flow control: NONE, XON/XOFF, RTS/CTS, DSR/DTR
		iotmo = 5000;			# I/O timeout, milliseconds (msec-s)

		rs485 = 0;			# 1: Enable RS485 specific support
	},

	{	desc = "Cisco Catalist 1900 Console";
		device = "/dev/ttyUSB1";	# OS device name, eg: COM1, /dev/ttyS0 ...
		chars = "9600, 8, N, 1";	# <Speed, bits in byte, parity checking, stop bits>
		flow = "NONE";			# Flow control: NONE, XON/XOFF, RTS/CTS, DSR/DTR
		iotmo = 5000;			# I/O timeout, milliseconds (msec-s)

		rs485 = 0;			# 1: Enable RS485 specific support
	}

);
