/*
**++
**  MODULE: N2S-MSGS,  IDENT: X.00-05,  REV: 00.05.00
**
**  FACILITY: A yet another Network to Serial gateway
**
**  DESCRIPTION: The message catalogue of the N2S facility (number 139). Every record is
**	FAO-styled and is signalled via $PUTMSG_FAO. New messages are added strictly at the end
**	of the __DEF_MESSAGES__ macro: the message numbers are generated by __COUNTER__ and must
**	stay stable between the deliveries.
**
**  AUTHORS: StarLet Squad and Ruslan R. Laishev (AKA: BadAss sysman)
**
**  MODIFICATION HISTORY:
**
**	25-AUG-2026	RRL	X.00-05 / REV: 00.05.00 - The catalogue is rewritten: the never used
**				printf-styled records (NETLSNR, NETERROR, RNF, NOLAN, LINKERR, CRCERR,
**				FULLMBAP, REVISION, LOGFILE) are removed, the FAO-styled records for the
**				operational troubleshooting are added and are signalled at the critical
**				places of N2S-MAIN, N2S-NET and N2S-TTY.
**
**--
*/

#ifndef	__N2S_MSGS__
#define __N2S_MSGS__	1

#include	"utility_routines.h"		/* STS$K-* constants */
#include	"defs.h"			/* N2S common definitions */

#ifdef __cplusplus
extern "C" {
#endif

#define	N2S		139			/* Facility number ! This number is should be unique */

/*	Attention !!! Place new messages at end of this macro !!! */
/*	<facility>, <severity>, <abbreviation>, <message text with the FAO directives> */

/*
 * ALL the records are FAO-styled and are signalled via $PUTMSG_FAO ONLY. See the User Guide
 * (docs/) for the per-code description.
 */
#define __DEF_MESSAGES__ \
\
$DEF_MSG(N2S, INFO,	REVISNF,		"Rev: !AC (REV: !AC)")\
$DEF_MSG(N2S, SUCCESS,	DEVREADY,		"Device <!AZ> [!UL baud, !UL!AZ!UL, flow: !AZ] --- is ready")\
$DEF_MSG(N2S, ERROR,	DEVOPNERR,		"Cannot open the device <!AZ>, errno: !SL")\
$DEF_MSG(N2S, SUCCESS,	LSNRRDY,		"[#!SL] Listener !%I:!UW [Target: <!AZ>] --- is ready")\
$DEF_MSG(N2S, ERROR,	LSNRERR,		"Listener !%I:!UW --- !AZ error, errno: !SL")\
$DEF_MSG(N2S, SUCCESS,	NETCONN,		"[#!SL] Accept client connection !%I:!UW (listener #!SL)")\
$DEF_MSG(N2S, SUCCESS,	NETDISCN,		"[#!SL] Disconnect client connection !AZ")\
$DEF_MSG(N2S, WARN,	DEVBUSY,		"[#!SL] Reject client !AZ --- device <!AZ> is busy with the session #!SL")\
$DEF_MSG(N2S, WARN,	SESSTMO,		"[#!SL] No activity for !UL seconds --- session is closed")\
$DEF_MSG(N2S, ERROR,	NETIOERR,		"[#!SL:<!AZ>] Network !AZ error, errno: !SL --- session is closed")\
$DEF_MSG(N2S, ERROR,	TTYIOERR,		"[#!SL:<!AZ>] Serial !AZ error, errno: !SL --- session is closed")\
$DEF_MSG(N2S, ERROR,	LINKDOWN,		"[#!SL:<!AZ>] Serial line failure (revents: !XW) --- session is closed")\
$DEF_MSG(N2S, INFO,	EXITST,			"Exit with exit_flag: !SL, rc: !XL")\




enum					/* Generate messages number constants */
{
	#define	$DEF_MSG(f, s, c, t)	f##$__##c = ( (f << 16) | (__COUNTER__<< 3) | STS$K_##s),
	__DEF_MESSAGES__
	#undef	$DEF_MSG

};


#ifdef __cplusplus
}
#endif

#endif	/*	__N2S_MSGS____	*/
